# Generated by Django 4.0.2 on 2022-09-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_create_Task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete')], default='INCOMPLETE', max_length=50),
        ),
    ]
