# Generated by Django 4.0.2 on 2022-09-18 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_Task_model__added_completion_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Task creation datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Task last modification datetime'),
        ),
    ]
